using Cinemachine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;


public partial class PlayerController : MonoBehaviour
{
    [SerializeField]
    private float playerHP = 100;
    public float PlayerHP { get { return playerHP; } }

    private Rigidbody rb;        // 2D Rigidbody »ēæė (3D¶óøé Rigidbody »ēæė)

    // ĄŌ·Ā °ü·Ć °ü·Ć
    private PlayerInput.PlayerActions PlayerInput { get { return GameManager.PlayerInputs; } }  // Input System Player ĄŌ·Ā                                                          

    private void Update()
    {
        PlayerMove();
        PlayerRotate();
    }

    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
        playerCam = GetComponentInChildren<CinemachineVirtualCamera>();
    }
}
